Enhavo\Bundle\SearchBundle\Entity\CronTask:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        commands:
            type: array
        ival:
            type: integer
        lastrun:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
