Enhavo\Bundle\SearchBundle\Entity\Dataset:
    type: entity
    table: search_dataset
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255

        reindex:
            type: integer

        reference:
            type: integer

    lifecycleCallbacks: {  }
