Enhavo\Bundle\SearchBundle\Entity\Index:
    type: entity
    table: search_index
    repositoryClass: Enhavo\Bundle\SearchBundle\Repository\IndexRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        word:
            type: string
            length: 255

        locale:
            type: string
            length: 255

        type:
            type: string
            length: 255

        score:
            type: float

    manyToOne:
        dataset:
            cascade: ['persist', 'refresh']
            targetEntity: Enhavo\Bundle\SearchBundle\Entity\Dataset

    lifecycleCallbacks: {  }
