parameters:
    enhavo_search.manager.class: Enhavo\Bundle\SearchBundle\Search\SearchManager

services:
    enhavo_search.manager:
        class: '%enhavo_search.manager.class%'
        arguments: [@doctrine.orm.entity_manager]

    enhavo_search.save_listener:
        class: Enhavo\Bundle\SearchBundle\EventListener\SaveListener
        arguments:
            - @service_container
            - %kernel.root_dir%
            - @request_stack
            - @doctrine.orm.entity_manager
        tags:
            - { name: kernel.event_listener, event: enhavo_app.create, method: onSave }
            - { name: kernel.event_listener, event: enhavo_app.update, method: onSave }