parameters:
    enhavo_search.manager.class: Enhavo\Bundle\SearchBundle\Search\SearchManager

services:
    enhavo_search.manager:
        class: '%enhavo_search.manager.class%'
        arguments: [@doctrine.orm.entity_manager]

    app.save_listener:
        class: Enhavo\Bundle\SearchBundle\EventListener\SaveListener
        tags:
            - { name: kernel.event_listener, event: save }