parameters:
    enhavo_search.manager.class: enhavo\SearchBundle\Search\SearchManager

services:
    enhavo_search.manager:
        class: '%enhavo_search.manager.class%'
        arguments: [@doctrine.orm.entity_manager]