services:
    enhavo_search.extractor_collector:
        class: Enhavo\Bundle\AppBundle\Type\TypeCollector
        arguments:
            - '@service_container'
            - 'Search Property Extractor'

    enhavo_search.extractor.extractor:
        class: Enhavo\Bundle\SearchBundle\Extractor\Extractor
        arguments:
            - '@enhavo_search.metadata.repository'
            - '@enhavo_search.extractor_collector'

    enhavo_search.extractor.property_extractor.model_extractor:
        class: Enhavo\Bundle\SearchBundle\Extractor\PropertyExtractor\ModelExtractor
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo_search.extractor, alias: model }

    enhavo_search.extractor.property_extractor.collection_extractor:
        class: Enhavo\Bundle\SearchBundle\Extractor\PropertyExtractor\CollectionExtractor
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo_search.extractor, alias: collection }

    enhavo_search.extractor.property_extractor.html_extractor:
        class: Enhavo\Bundle\SearchBundle\Extractor\PropertyExtractor\HtmlExtractor
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo_search.extractor, alias: html }

    enhavo_search.extractor.property_extractor.text_extractor:
        class: Enhavo\Bundle\SearchBundle\Extractor\PropertyExtractor\TextExtractor
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo_search.extractor, alias: text }