services:
    enhavo_search.filter_provider_collector:
        class: Enhavo\Bundle\AppBundle\Type\TypeCollector
        arguments:
            - '@service_container'
            - 'Search Filter Provider'

    Enhavo\Bundle\SearchBundle\Filter\FilterData:
        public: true
        arguments:
            - '@enhavo_search.metadata.repository'
            - '@enhavo_search.filter_provider_collector'

    Enhavo\Bundle\SearchBundle\Filter\DataProvider\ValueDataProvider:
        public: true
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo_search.filter_provider, alias: 'value' }

    Enhavo\Bundle\SearchBundle\Filter\DataProvider\PropertyDataProvider:
        public: true
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo_search.filter_provider, alias: 'property' }

    Enhavo\Bundle\SearchBundle\Filter\DataProvider\DateDataProvider:
        public: true
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo_search.filter_provider, alias: 'date' }