services:
    enhavo_search.save_listener:
        class: Enhavo\Bundle\SearchBundle\EventListener\SaveListener
        calls:
            - [ 'setContainer', [ '@service_container' ]]
        tags:
            - { name: kernel.event_listener, event: enhavo_app.post_create, method: onSave }
            - { name: kernel.event_listener, event: enhavo_app.post_update, method: onSave }

    enhavo_search.delete_listener:
        class: Enhavo\Bundle\SearchBundle\EventListener\DeleteListener
        arguments:
            - '@service_container'
            - '@enhavo_search.metadata.metadata_factory'
        tags:
            - { name: kernel.event_listener, event: enhavo_app.pre_delete, method: onDelete }
