language: php

dist: xenial

php:
  - 7.2

env:
  - ENVIRONMENT=test DEBUG=true

before_install:
    - composer self-update
    - if [[ ! -z "$GITHUB_OAUTH_TOKEN" ]]; then composer config -g github-oauth.github.com "$GITHUB_OAUTH_TOKEN" >/dev/null 2>&1; fi
    - export USE_ZEND_ALLOC=0
    
install:
    - composer install --no-interaction --optimize-autoloader --prefer-dist

before_script:
    - php -v
    - php -i | grep -v GITHUB_OAUTH_TOKEN

script:
  - vendor/bin/phpunit --stop-on-failure