Enhavo\Bundle\SearchBundle\Model\Database\Index:
    type: entity
    table: search_index
    repositoryClass: Enhavo\Bundle\SearchBundle\Repository\IndexRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        word:
            type: string
            length: 255
            nullable: true
        locale:
            type: string
            length: 255
            nullable: true
        weight:
            type: integer
            nullable: true
        score:
            type: float
            nullable: true
    manyToOne:
        dataSet:
            targetEntity: Enhavo\Bundle\SearchBundle\Model\Database\DataSet
            inversedBy: indexes
            joinColumn:
                onDelete: CASCADE

    lifecycleCallbacks: {  }
